# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-26 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bubye',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recv', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=5000)),
            ],
        ),
    ]
