# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-30 08:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0005_auto_20170430_0021'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='bubye',
            name='alumini',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='message.List'),
        ),
    ]
